{% set name = "lazypredict" %}
{% set version = "0.2.12" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/lazypredict-{{ version }}.tar.gz
  sha256: f97797c3afe9ef5bebda3677eeb46e84c4291f0dac9f824105f509e4e8d234f5

build:
  number: 1
  noarch: python
  entry_points:
    - lazypredict=lazypredict.cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest-runner
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - click
    - pandas
    - scikit-learn
    - tqdm
    - joblib
    - lightgbm
    - xgboost
    
test:
  imports:
    - lazypredict
  commands:
    - lazypredict --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/shankarpandala/lazypredict
  summary: Rapid low code ML testing with multiple basic models
  license: MIT
  license_file: LICENSE
  description: |
    Lazy Predict help build a lot of basic models without much code and helps
     understand which models works better without any parameter tuning

extra:
  recipe-maintainers:
    - thewchan
