{% set name = "lazypredict" %}
{% set version = "0.2.16" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/lazypredict-{{ version }}.tar.gz
  sha256: e46361d959785918d7ce86ddfb522dc00e2da4418d46833e702d5c6ef8244ff5

build:
  number: 0
  noarch: python
  entry_points:
    - lazypredict=lazypredict.cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest-runner
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - click
    - pandas
    - scikit-learn
    - tqdm
    - joblib
    - lightgbm
    - xgboost
    - pytest-runner
    - mlflow >=2.0.0

test:
  imports:
    - lazypredict
  commands:
    - lazypredict --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/shankarpandala/lazypredict
  summary: Rapid low code ML testing with multiple basic models
  license: MIT
  license_file: LICENSE
  description: |
    Lazy Predict help build a lot of basic models without much code and helps
     understand which models works better without any parameter tuning

extra:
  recipe-maintainers:
    - thewchan
